spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: rules-service
              uri: http://rules-service:8081
              predicates:
                - Path=/rules/**
              filters:
                - StripPrefix=1

            - id: decision-service
              uri: http://decision-service:8082
              predicates:
                - Path=/decisions/**
              filters:
                - StripPrefix=0

            - id: audit-service
              uri: http://audit-service:8083
              predicates:
                - Path=/audit/**
              filters:
                - StripPrefix=1
server:
  port: 8080