spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  flyway:
    baseline-on-migrate: true
  application:
    name: rules-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
#  datasource:
#    url: jdbc:h2:mem:ruleservicedb
#    driver-class-name: org.h2.Driver
#    username: ruleservice
#    password: ruleservice
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    defer-datasource-initialization: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: false
