spring:
  application:
    name: decision-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: decision-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.rodrigomoran.decisionplatform.decision_service.infrastructure.messaging.dto"
        spring.json.value.default.type: com.rodrigomoran.decisionplatform.decision_service.infrastructure.messaging.dto.RulePublishedEventPayload

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      ack-mode: record

server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.rodri.decisionservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
springdoc:
#  packages-to-scan: com.rodrigomoran.decisionplatform.decision_service.interfaces.rest
#  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html
#    disable-swagger-default-url: true
